[package]
name = "bilibilive-clidm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = "1.0.202"
serde_json = "1.0.117"
bytes = "1.6.0"
tokio-tungstenite = "*"
reqwest = { version = "0.12", features = ["json"] }
